import os
from google import genai
from dotenv import load_dotenv

load_dotenv()
API_KEY = os.getenv('GENAI_API_KEY')

def gemini_correct(text: str, model="gemini-3-flash-preview"):
    """
    Docstring for gemini_correct
    
    :param text: The text you want to correct
    :param model: The model to use for generating the response
    :return: The response generated by Gemini
    """
    client = genai.Client(api_key=API_KEY)
    prompt = f"""
You are a helpful assistant that corrects dyslexia-related writing errors.

Rules:
- Fix spelling, grammar, and word order
- Do not replace words like "gonna", "wanna", "kinda", "wasnt", "isnt" etc. with their formal counterparts unless they are used in a way that is grammatically incorrect
- Also ignore missing pronouns, articles, and conjunctions if the sentence is still understandable without them
- Preserve original meaning and tone
- Do NOT over-rewrite or paraphrase heavily
- Return ONLY the corrected sentence

Text:
{text}
"""
    
    response = client.models.generate_content(
        model=model,
        contents=prompt
    )

    return response.text.strip()